In [3]:
# get an example of data
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df = pd.read_csv('../extracted_data/mongodb/db/2001.csv')
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Id
0,2020,1,1,17,5,2020-01-17,B6,20409,B6,N661JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,33,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,11,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,15.0,1941.0,2212.0,6.0,2229,2218.0,-11.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,172.0,151.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,0
1,2020,1,1,19,7,2020-01-19,B6,20409,B6,N662JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,33,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,11,1940,1947.0,7.0,7.0,0.0,0.0,1900-1959,11.0,1958.0,2217.0,6.0,2229,2223.0,-6.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,156.0,139.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,2
2,2020,1,1,21,2,2020-01-21,B6,20409,B6,N784JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,33,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,11,1940,1952.0,12.0,12.0,0.0,0.0,1900-1959,10.0,2002.0,2229.0,6.0,2229,2235.0,6.0,6.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,163.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,4
3,2020,1,1,23,4,2020-01-23,B6,20409,B6,N806JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,33,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,11,1940,1923.0,-17.0,0.0,0.0,-2.0,1900-1959,13.0,1936.0,2153.0,8.0,2229,2201.0,-28.0,0.0,0.0,-2.0,2200-2259,0.0,NaN,0.0,169.0,158.0,137.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,6
4,2020,1,1,25,6,2020-01-25,B6,20409,B6,N624JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,33,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,11,1940,1931.0,-9.0,0.0,0.0,-1.0,1900-1959,13.0,1944.0,2200.0,10.0,2229,2210.0,-19.0,0.0,0.0,-2.0,2200-2259,0.0,NaN,0.0,169.0,159.0,136.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,8

In [8]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

In [3]:
# initialize spark session
spark = SparkSession \
        .builder \
        .master("local[*]") \
        .appName("StagingToWarehouse") \
        .config("spark.executor.memory", "2g") \
        .config("spark.executor.cores", '2') \
        .config("spark.driver.memory", '2g') \
        .config("spark.driver.cores", '2') \
        .config("spark.cassandra.connection.host", "localhost") \
        .config("spark.cassandra.connection.port", "9042") \
        .config("spark.cassandra.auth.username", "root") \
        .config("spark.cassandra.auth.password", "admin") \
        .config("spark.jars", "../../tools/spark-jars/spark-3.3-bigquery-0.31.1.jar") \
        .config("spark.hadoop.google.cloud.auth.service.account.enable", "true") \
        .config("spark.hadoop.google.cloud.auth.service.account.json.keyfile", "../../tools/bigquery/key_file.json") \
        .getOrCreate()
# define the project-id to be used
project='test-373705'

In [48]:
id_set_bq_fact_records = spark.read \
                        .format("bigquery") \
                        .options(parentProject=project) \
                        .options(table='flight_delay.fact_records') \
                        .load("id") \
                        .rdd.flatMap(lambda x: x) \
                        .distinct() \
                        .collect()

In [49]:
id_set_bq_fact_records

[]

In [50]:
cs_mysql = spark.read \
        .format("org.apache.spark.sql.cassandra") \
        .options(keyspace="flight_delay", table="mysql") \
        .load() \
        .filter(~col('id').isin(id_set_bq_fact_records))

In [51]:
cs_mysql.printSchema()

root
 |-- id: long (nullable = false)
 |-- actualelapsedtime: double (nullable = true)
 |-- airtime: double (nullable = true)
 |-- arrdel15: double (nullable = true)
 |-- arrdelay: double (nullable = true)
 |-- arrdelayminutes: double (nullable = true)
 |-- arrivaldelaygroups: double (nullable = true)
 |-- arrtime: double (nullable = true)
 |-- arrtimeblk: string (nullable = true)
 |-- cancellationcode: string (nullable = true)
 |-- cancelled: double (nullable = true)
 |-- carrierdelay: double (nullable = true)
 |-- crsarrtime: long (nullable = true)
 |-- crsdeptime: long (nullable = true)
 |-- crselapsedtime: double (nullable = true)
 |-- dayofmonth: long (nullable = true)
 |-- dayofweek: long (nullable = true)
 |-- departuredelaygroups: double (nullable = true)
 |-- depdel15: double (nullable = true)
 |-- depdelay: double (nullable = true)
 |-- depdelayminutes: double (nullable = true)
 |-- deptime: double (nullable = true)
 |-- deptimeblk: string (nullable = true)
 |-- dest: string (nullable = true)
 |-- destairportid: long (nullable = true)
 |-- destairportseqid: long (nullable = true)
 |-- destcitymarketid: long (nullable = true)
 |-- destcityname: string (nullable = true)
 |-- deststate: string (nullable = true)
 |-- deststatefips: long (nullable = true)
 |-- deststatename: string (nullable = true)
 |-- destwac: long (nullable = true)
 |-- distance: double (nullable = true)
 |-- distancegroup: long (nullable = true)
 |-- diverted: double (nullable = true)
 |-- dot_id_reporting_airline: long (nullable = true)
 |-- flight_number_reporting_airline: long (nullable = true)
 |-- flightdate: string (nullable = true)
 |-- flights: double (nullable = true)
 |-- iata_code_reporting_airline: string (nullable = true)
 |-- lateaircraftdelay: double (nullable = true)
 |-- month: long (nullable = true)
 |-- nasdelay: double (nullable = true)
 |-- origin: string (nullable = true)
 |-- originairportid: long (nullable = true)
 |-- originairportseqid: long (nullable = true)
 |-- origincitymarketid: long (nullable = true)
 |-- origincityname: string (nullable = true)
 |-- originstate: string (nullable = true)
 |-- originstatefips: long (nullable = true)
 |-- originstatename: string (nullable = true)
 |-- originwac: long (nullable = true)
 |-- quarter: long (nullable = true)
 |-- reporting_airline: string (nullable = true)
 |-- securitydelay: double (nullable = true)
 |-- tail_number: string (nullable = true)
 |-- taxiin: double (nullable = true)
 |-- taxiout: double (nullable = true)
 |-- weatherdelay: double (nullable = true)
 |-- wheelsoff: double (nullable = true)
 |-- wheelson: double (nullable = true)
 |-- year: long (nullable = true)

In [27]:
cs_mysql.show(1)

23/06/30 11:18:33 WARN CqlRequestHandler: Query '[2 values] SELECT "id", "actualelapsedtime", "airtime", "arrdel15", "arrdelay", "arrdelayminutes", "arrivaldelaygroups", "arrtime", "arrtimeblk", "cancellationcode", "cancelled", "carrierdelay", "crsarrtime", "crsdeptime", "crselapsedtime", "dayofmonth", "dayofweek", "departuredelaygroups", "depdel15", "depdelay", "depdelayminutes", "deptime", "deptimeblk", "dest", "destairportid", "destairportseqid", "destcitymarketid", "destcityname", "deststate", "deststatefips", "deststatename", "destwac", "distance", ...<truncated> ["partition key token"=2149845809422670751, "partition key token"=3039162959834464315]' generated server side warning(s): Read 1000 live rows and 6707 tombstone cells for query SELECT actualelapsedtime, airtime, arrdel15, arrdelay, arrdelayminutes, arrivaldelaygroups, arrtime, arrtimeblk, cancellationcode, cancelled, carrierdelay, crsarrtime, crsdeptime, crselapsedtime, dayofmonth, dayofweek, departuredelaygroups, depdel15, depdelay, depdelayminutes, deptime, deptimeblk, dest, destairportid, destairportseqid, destcitymarketid, destcityname, deststate, deststatefips, deststatename, destwac, distance, distancegroup, diverted, dot_id_reporting_airline, flight_number_reporting_airline; token 2168251003505685335 (see tombstone_warn_threshold)
23/06/30 11:18:33 WARN CqlRequestHandler: Query '[2 values] SELECT "id", "actualelapsedtime", "airtime", "arrdel15", "arrdelay", "arrdelayminutes", "arrivaldelaygroups", "arrtime", "arrtimeblk", "cancellationcode", "cancelled", "carrierdelay", "crsarrtime", "crsdeptime", "crselapsedtime", "dayofmonth", "dayofweek", "departuredelaygroups", "depdel15", "depdelay", "depdelayminutes", "deptime", "deptimeblk", "dest", "destairportid", "destairportseqid", "destcitymarketid", "destcityname", "deststate", "deststatefips", "deststatename", "destwac", "distance", ...<truncated> ["partition key token"=2149845809422670751, "partition key token"=3039162959834464315]' generated server side warning(s): Read 1000 live rows and 6639 tombstone cells for query SELECT actualelapsedtime, airtime, arrdel15, arrdelay, arrdelayminutes, arrivaldelaygroups, arrtime, arrtimeblk, cancellationcode, cancelled, carrierdelay, crsarrtime, crsdeptime, crselapsedtime, dayofmonth, dayofweek, departuredelaygroups, depdel15, depdelay, depdelayminutes, deptime, deptimeblk, dest, destairportid, destairportseqid, destcitymarketid, destcityname, deststate, deststatefips, deststatename, destwac, distance, distancegroup, diverted, dot_id_reporting_airline, flight_number_reporting_airline; token 2186332302569663196 (see tombstone_warn_threshold)
+------+-----------------+-------+--------+--------+---------------+------------------+-------+----------+----------------+---------+------------+----------+----------+--------------+----------+---------+--------------------+--------+--------+---------------+-------+----------+----+-------------+----------------+----------------+--------------+---------+-------------+-------------+-------+--------+-------------+--------+------------------------+-------------------------------+----------+-------+---------------------------+-----------------+-----+--------+------+---------------+------------------+------------------+--------------+-----------+---------------+---------------+---------+-------+-----------------+-------------+-----------+------+-------+------------+---------+--------+----+
|    id|actualelapsedtime|airtime|arrdel15|arrdelay|arrdelayminutes|arrivaldelaygroups|arrtime|arrtimeblk|cancellationcode|cancelled|carrierdelay|crsarrtime|crsdeptime|crselapsedtime|dayofmonth|dayofweek|departuredelaygroups|depdel15|depdelay|depdelayminutes|deptime|deptimeblk|dest|destairportid|destairportseqid|destcitymarketid|  destcityname|deststate|deststatefips|deststatename|destwac|distance|distancegroup|diverted|dot_id_reporting_airline|flight_number_reporting_airline|flightdate|flights|iata_code_reporting_airline|lateaircraftdelay|month|nasdelay|origin|originairportid|originairportseqid|origincitymarketid|origincityname|originstate|originstatefips|originstatename|originwac|quarter|reporting_airline|securitydelay|tail_number|taxiin|taxiout|weatherdelay|wheelsoff|wheelson|year|
+------+-----------------+-------+--------+--------+---------------+------------------+-------+----------+----------------+---------+------------+----------+----------+--------------+----------+---------+--------------------+--------+--------+---------------+-------+----------+----+-------------+----------------+----------------+--------------+---------+-------------+-------------+-------+--------+-------------+--------+------------------------+-------------------------------+----------+-------+---------------------------+-----------------+-----+--------+------+---------------+------------------+------------------+--------------+-----------+---------------+---------------+---------+-------+-----------------+-------------+-----------+------+-------+------------+---------+--------+----+
|526875|             42.0|   30.0|     0.0|    -4.0|            0.0|              -1.0| 2331.0| 2300-2359|            null|      0.0|        null|      2335|      2342|          53.0|        30|        4|                 0.0|     0.0|     7.0|            7.0| 2349.0| 2300-2359| BHM|        10599|         1059904|           30599|Birmingham, AL|       AL|            1|      Alabama|     51|   134.0|            1|     0.0|                   19790|                           2436|2020-01-30|    1.0|                         DL|             null|    1|    null|   ATL|          10397|           1039707|             30397|   Atlanta, GA|         GA|             13|        Georgia|       34|      1|               DL|         null|     N912DE|   2.0|   10.0|        null|   2359.0|  2329.0|2020|
+------+-----------------+-------+--------+--------+---------------+------------------+-------+----------+----------------+---------+------------+----------+----------+--------------+----------+---------+--------------------+--------+--------+---------------+-------+----------+----+-------------+----------------+----------------+--------------+---------+-------------+-------------+-------+--------+-------------+--------+------------------------+-------------------------------+----------+-------+---------------------------+-----------------+-----+--------+------+---------------+------------------+------------------+--------------+-----------+---------------+---------------+---------+-------+-----------------+-------------+-----------+------+-------+------------+---------+--------+----+
only showing top 1 row

In [ ]:
cs_mysql

In [2]:
spark.stop()